---
title: "Preserving Survey Data"
author: 
  - "Lars Vilhuber"
  - "Laurel Krovetz"
date: August 26 2025
format: 
  revealjs:
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    theme: [night, style.css]
    self_contained: false
    logo: logo.png
    footer: ""
    reveal_options:
        slideNumber: true
        previewLinks: false
        chalkboard:
          theme: chalkboard
          toggleNotesButton: true
    reveal_plugins: ["chalkboard"]

---


```{r config,include=FALSE}
source(here::here("presentation",'global-libraries.R'))
# The repository name

message(Sys.getenv("GITHUB_REPOSITORY"))

# Process the repository name to generate the URL
# - split the two components
# - combine them into a URL with 'github.io' in the middle

SUBDIRECTORY <- "presentation/presentation.html" # Leave this empty if this file is in the main directory of the repository

GITHUB_REPOSITORY <- Sys.getenv("GITHUB_REPOSITORY")
GITHUB_REPOSITORY_PARTS <- strsplit(GITHUB_REPOSITORY, "/")[[1]]
REPOSITORY_URL <- paste0("https://github.com/", GITHUB_REPOSITORY)

WEBSITE_URL <- paste0("https://", GITHUB_REPOSITORY_PARTS[1], ".github.io/", GITHUB_REPOSITORY_PARTS[2], "/", SUBDIRECTORY)
WEBSITE_SHORT <- paste0(GITHUB_REPOSITORY_PARTS[1], ".github.io/", GITHUB_REPOSITORY_PARTS[2], "/", SUBDIRECTORY)

```

```{r, child=c(here::here("presentation",'00-introduction1.md'))}
```

```{r, child=c(here::here("presentation",'00-introduction2.md'))}
```

```{r, child=c(here::here("presentation",'00-survey-qrcode.md'))}
```

```{r, child=c(here::here("presentation",'01-goals.md'))}
```

# Creating a survey in Qualtrics

```{r, child=c(here::here("presentation",'10-creating-survey.md'))}
```

```{r, child=c(here::here("presentation",'11-qualtrics-data.md'))}
```

# Processing data in R

```{r, child=c(here::here("presentation",'20-processing-R.md'))}
```

```{r, child=c(here::here("presentation",'21-API-key.md'))}
```

```{r, child=c(here::here("presentation",'22-loading-data-R.md'))}
```

```{r, child=c(here::here("presentation",'23-cleaning-R.md'))}
```

```{r, child=c(here::here("presentation",'24-processing-R.md'))}
```

```{r, child=c(here::here("presentation",'30-present-data.md'))}
```

# Survey results
```{r, child=c(here::here("presentation",'40-survey-results.md'))}
```

# Keeping your secrets secret
```{r, child=c(here::here("presentation",'50-secrets.md'))}
```

```{r, child=c(here::here("presentation",'51-API-key-secret.md'))}
```

```{r, child=c(here::here("presentation",'52-API-key-workflow.md'))}
```

```{r, child=c(here::here("presentation",'end.md'))}
```
